### ISSUE TITLE
Prueba comenzado así el archivo CRUD.py

### ISSUE THREAD

**Issue by Makova** [jgarciagimenez/CRUD#1]
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk
import MySQLdb as db

# Database 
db_host = "localhost"
db_user = "crud"
db_pass = "crud"
db_data = "CRUD"
```

**Comment by jgarciagimenez** [comment]
Gracias, ya he arreglado eso.

**Comment by Makova** [comment]
Ok :+1

**Comment by Makova** [comment]
Lo reabro, sigue fallando en el que acabo de bajar.

**Comment by Makova** [comment]
La única manera de que me abra (menu_CRUD.glade) es añadiendo las líneas que he puesto al crear este Issue, y aún así, la ventana con Glade aparece pero no deja escribir en ella.

**Comment by jgarciagimenez** [comment]
Que problema le da exactamente?  A mi me funciona correctamente, pero lo estoy haciendo en Windows.  
En la ventana principal no está hecho para escribir,  la entrada de los datos esta hecha con ventanas que se abren al clickar en las opciones del menú.  Si le da a crear se abre una ventana para ingresar los datos que quiera insertar.

**Comment by Makova** [comment]
El problema es que sólo abre la ventana y no deja hacer nada más. ¿Qué versión de Python llevas instalada?.
[!](http://i65.tinypic.com/15n6fwl.png)

**Comment by Makova** [comment]
Pero eso sale cambiando tu ejercicio CRUD.py en las primeras líneas de tú código:
`from gi.repository import Gtk

import MySQLdb

Conexion = MySQLdb.connect(host='localhost', user='jose',passwd='cine', db='DBdePeliculas')
micursor = Conexion.cursor(MySQLdb.cursors.DictCursor)`

Por estas:
`import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk
import MySQLdb as db

# Database 
db_host = "localhost"
db_user = "crud"
db_pass = "crud"
db_data = "CRUD"`

**Comment by jgarciagimenez** [comment]
Perdone, cuando le he dicho que lo había arreglado me había dado un error al subirlo a github y solo tenía los cambios en el repositorio en local. Ahora está en gitgub también, de todos modos a mi si me funcionan todas las opciones del menu de acciones.

![dialogs](https://cloud.githubusercontent.com/assets/17472444/16209672/676712e0-3738-11e6-8cef-678bc4b6c9c1.PNG)

La versión de python que tengo es la 2.7.11

**Comment by Makova** [comment]
Aún así va a mirar y ejecutar el código otro profesor.

**Comment by Makova** [comment]
Ok, lo vuelvo a probar.

**Comment by Makova** [comment]
Muy bien, quitando las líneas de conexión en local, funciona de 10:
`Conexion = db.connect(db_host,db_user,db_pass,db_data)
micursor = Conexion.cursor(db.cursors.DictCursor)`
Excelente trabajo :100:
